# Search
[[mgr.prepend_keymap]]
on = "s"
run = "search --via=fd --args='--full-path'"
desc = "Search files by name via fd"

[[mgr.prepend_keymap]]
on = "z"
run = "plugin fzf"
desc = "Jump to a file/directory via fzf"

[[mgr.prepend_keymap]]
on = "Z"
run = "plugin zoxide"
desc = "Jump to a directory via zoxide"

# Run shell
[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"

# smart-enter: https://github.com/yazi-rs/plugins/tree/main/smart-enter.yazi
[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# chmod: https://github.com/yazi-rs/plugins/tree/main/chmod.yazi
[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"
